#!/bin/bash
TIME=$(date +"%F %H:%M.%S")
LOG_MESSAGE="$TIME $$ ${LOGNAME:-x} $0 $*"
DIR="/home/xpopovi1/pv004lab/studis_data"
FACULTY="$DIR/faculty.txt"
LOG="$DIR/log"
USAGE="Usage: $0"
FORCE=1

usage()
{
	>&2 echo $USAGE
	exit 1
}

fakulta_nova()
{
	if [ ${#1} -gt 8 ]; then usage; fi
	if [[ $1 != *[A-Za-z0-9]* ]]; then usage; fi
	if [[ $2 != *[A-Za-z0-9]* ]] && [[ $2 != *" :;,-/()@?"* ]]; then echo ahoj; usage; fi
	if grep -q "^$1#" $FACULTY; then usage; fi
	echo "$1#$2" >> $FACULTY
}

fakulta_vypis()
{
	echo "Fakulta  | Název"
	if [ $# -eq 1 ]
	then
		ID=$(grep "^$1#" $FACULTY | cut -d# -f1)
		NAME=$(grep "^$1#" $FACULTY | cut -d# -f2)
		printf "%-8s | %s\n" "$ID" "$NAME"
	else
		echo "--------------------------"
		while read line
		do
			ID=$(echo $line | cut -d# -f1)
			NAME=$(echo $line | cut -d# -f2) 
			printf "%-8s | %s\n" "$ID" "$NAME"
		done < $FACULTY | sort -t$'#' -k 1
	fi	
}

fakulta_smaz()
{
	if grep -q "^$1#" $FACULTY
	then
		sed -i "/^$1#/d" $FACULTY
	else
		usage
	fi
}

fakulta_nazev()
{
	if grep -q "^$1#" $FACULTY
	then
		sed -i "s/^$1#.*\$/$1#$2/" $FACULTY
	else
		usage
	fi
}

domaci_ukol()
{
	COUNTER=0
	for file in "$@"
	do
		COUNTER=$((COUNTER+$(grep '^null,' $file | wc -l)))
	done
	echo $COUNTER
}

while getopts 'd:f' option
do
	case "$option" in
		d)	DIR="$OPTARG"
			if [ "${DIR: -1}" == "/" ]; then DIR="${DIR::-1}"; fi
			if [ -d "$DIR" ] && ! [ -w "$DIR" ]; then usage; fi
			FACULTY="$DIR/faculty.txt"
			LOG="$DIR/log";;
		f)	FORCE=0;;
		?)	usage;;
	esac
done
shift $(($OPTIND-1))

mkdir -p $DIR
if [ $? -ne 0 ]; then usage; fi
touch $FACULTY
#if [ $? -ne 0 ]; then usage; fi
echo $LOG_MESSAGE >> $LOG

if [ $# -eq 0 ]; then usage; fi
case "$1" in
	cesta-adresář|cesta-adresar)
		if [ $# -ne 1 ]; then usage; fi
		echo $DIR;;
	smaž-adresář|smaz-adresar)
		if [ $# -ne 1 ] || [ $FORCE -ne 0 ]; then usage; fi
		rm -r $DIR;;
	dej-log)
		if [ $# -gt 2 ]; then usage; fi
		if [ $# -eq 1 ]
		then
			cat $LOG
		else
			egrep "$2" $LOG
		fi;;
	pomoc)
		if [ $# -ne 1 ]; then usage; fi
		echo $USAGE;;
	fakulta-nová|fakulta-nova)
		if [ $# -ne 3 ]; then usage; fi
		fakulta_nova "$2" "$3";;
	fakulta-výpis|fakulta-vypis)
		if [ $# -eq 1 ]; then fakulta_vypis; fi
		if [ $# -eq 2 ]; then fakulta_vypis "$2"; fi
		if [ $# -gt 2 ]; then usage; fi;;
	fakulta-smaž|fakulta-smaz)
		if [ $# -ne 2 ]; then usage; fi
		fakulta_smaz "$2";;
	fakulta-název|fakulta-nazev)
		if [ $# -ne 3 ]; then usage; fi
		fakulta_nazev "$2" "$3";;
	domácí-úkol)
		if [ $# -lt 2 ]; then usage; fi
		shift
		domaci_ukol "$@";;
	*)
		usage;;
esac
